version: '3.8'

services:

  strategy_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dk5f95/strategy-manager
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8001
    volumes:
      - /Volumes/MyLab/freelance/strategyManager:/app
    restart: on-failure
    ports:
      - 8001:8001
    networks:
      - strategy-network

#  redis:
#    image: redis:latest
#    ports:
#      - 6378:6379
#    depends_on:
#      - rabbitmq

  strategy-celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: dk5f95/strategy-celery-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    networks:
      - strategy-network

#  strategy-celery-beat:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    image: dk5f95/strategy-celery-beat
#    command: /start-celerybeat
#    depends_on:
#      - strategy-celery-worker
#      - rabbitmq
#    networks:
#      - strategy-network

  rabbitmq:
      image: "rabbitmq:3.8-management"
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672

      volumes:
          - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
          - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      networks:
        - strategy-network

networks:
  strategy-network:
    driver: bridge
