  rabbitmq:
      image: "rabbitmq:3.8-management"
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
          - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      networks:
        - strategy-network