MONGO_OHLCV_DATA_CONFIG_COLLECTION = "ohlcvConfig"
MONGO_OHLCV_COLLECTION_T_DESC_INDEX_NAME = "t_-1_s_1"


MONGO_STRATEGY_SAVED_DATA = "strategySavedData"

PLATFORM_BINANCE = "binance"
PANDAS_TO_OHLCV_TIMEFRAME_MAP = {"D": "1d", "1min": "1m", "15min": "15m"}
